version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: docutils
    versions:
    - "0.17"
  - dependency-name: sphinx
    versions:
    - 3.5.0
    - 3.5.3
  - dependency-name: pygments
    versions:
    - 2.8.0
  - dependency-name: urllib3
    versions:
    - 1.26.3
